### ISSUE TITLE
constructors

### ISSUE THREAD

**Issue by hautran1993** [iAmWillShepherd/ama#1]
he will i'm having a hard time understanding how to plan out my code to work accordingly. for example: the node hangman game
i don't under stand the planning of creating enough functions to make it work smoothly. i always put if statements in wrong places. and don't know exactly when to use for loops. i know what it does, but i don't exactly when to use it.

any advice would be apprectieated

**Comment by iAmWillShepherd** [comment]
Ok so, I'm going to break your question down into 3 parts. 

* Knowing when to extract code into a function
* Knowing when to use conditional statements
* Knowing when to use loops

Does this correctly summarize what you are asking? 

Also, your issue body is constructors. Is there anything specific about constructors you're interested in?

**Comment by hautran1993** [comment]
yes, it does.

Using constructors in forms of function and how it connects together. I'm having a hard time grasping the concepts and how function inside of constructors could go together.

**Comment by iAmWillShepherd** [comment]
So, for constructors, the confusion is around having a function within a function (remember a constructor in JS is just a function)?

**Comment by hautran1993** [comment]
my question should be why. like why would you want inside the constructor . rather than just using regular function?

**Comment by iAmWillShepherd** [comment]
So the reason why you'd have functions inside of a constructor function is so that new instances of your newly constructed objects have access to the functions to mutate its internal state.

Consider this example:

```js
function Car(make, model) {
  this.make = make
  this.model = model
  this.isRunning = false

  function start() {
    if (this.isRunning) {
      throw new Error("Cannot start that is already running")
    }

    this.isRunning = true
  }

  function turnOff() {
    if (!this.isRunning) {
      throw new Error("Cannot turn off a car that is already off")
    }

    this.isRunning = false
  }

  function getStatus() {
    const engineStatus = this.isRunning ? "running" : "turned off"

    return `Your ${make} ${model} is ${engineStatus}.`
  }
}

const car = new Car("Mercedes Benz", "AMG C63s Coupe")
```

The newly constructed object, `car` has access to all of the functions defined in the `Car` constructor function. That means I can do the following: `car.start()`. 

In summary, we keep the functions in the constructor function because they are related. Additionally, all newly constructed instances of `Car` _should_ have these functions *and*, since they exist in the constructor function, we only need to write them once; all instances of `Car` will be able to take advantage of any updates we make to `Car`.
